# 記事詳細(Issue詳細)
query IssueDetail($id: ID!) {
  node(id: $id) {
    ... on Issue {
      id
      title
      body
      bodyHTML
      labels(first: 5) {
        nodes {
          color
          id
          name
        }
      }
      updatedAt
      closed
      projectItems(first: 1) {
        totalCount
        nodes {
          fieldValueByName(name: "Status") {
            ... on ProjectV2ItemFieldSingleSelectValue {
              id
              name
            }
          }
        }
      }
      comments(first: 1) {
        nodes {
          body
        }
      }
    }
  }
}
