# タグ
query LifeRepositoryLabels($id: ID = "R_kgDOIKnT4g") {
  node(id: $id) {
    ... on Repository {
      id
      name
      labels(first: 50) {
        nodes {
          color
          id
          name
          updatedAt
        }
      }
    }
  }
}
