// TODO: 別の管理方法を探りたい
export const MASTER_TAGS = [
  {
    id: "0",
    name: "React",
    color: "5fd9fb",
    categoryId: "0",
  },
  {
    id: "1",
    name: "Next.js",
    color: "C53030",
    categoryId: "0",
  },
  {
    id: "4",
    name: "カードマジック",
    color: "9B2C2C",
    categoryId: "2",
  },
  {
    id: "5",
    name: "コインマジック",
    color: "E53E3E",
    categoryId: "2",
  },
  {
    id: "6",
    name: "Chakra UI",
    color: "4ac7c1",
    categoryId: "0",
  },
  {
    id: "8",
    name: "アーマード・コア",
    color: "42bff8",
    categoryId: "3",
  },
  {
    id: "9",
    name: "ナガノのくま",
    color: "f9c848",
    categoryId: "4",
  },
  {
    id: "10",
    name: "ナガノマーケット",
    color: "ffec82",
    categoryId: "4",
  },
  {
    id: "11",
    name: "福袋",
    color: "fb6423",
    categoryId: "4",
  },
  {
    id: "12",
    name: "ちいかわ",
    color: "0b9fd9",
    categoryId: "4",
  },
  {
    id: "13",
    name: "デックレビュー",
    color: "58427c",
    categoryId: "2",
  },
  {
    id: "14",
    name: "マジック修行",
    color: "d83473",
    categoryId: "2",
  },
  {
    id: "15",
    name: "node-sass",
    color: "fcc800",
    categoryId: "0",
  },
  {
    id: "16",
    name: "Nuxt",
    color: "00b068",
    categoryId: "0",
  },
  {
    id: "17",
    name: "振り返り",
    color: "ccff99",
    categoryId: "4",
  },
  {
    id: "18",
    name: "GTM",
    color: "4285f4",
    categoryId: "0",
  },
  {
    id: "19",
    name: "GA",
    color: "e37400",
    categoryId: "0",
  },
  {
    id: "20",
    name: "Vercel",
    color: "7928ca",
    categoryId: "0",
  },
  {
    id: "21",
    name: "Amplify",
    color: "cc7a00",
    categoryId: "0",
  },
  {
    id: "22",
    name: "App Runner",
    color: "cc7a00",
    categoryId: "0",
  },
  {
    id: "23",
    name: "AWS",
    color: "cc7a00",
    categoryId: "0",
  },
];
