# 記事一覧(Issue一覧)
query LifeProjectIssues($first: Int, $last: Int, $before: String, $after: String) {
  node(id: "PVT_kwHOAkr4os4AHb3E") {
    ... on ProjectV2 {
      id
      items(
        first: $first
        last: $last
        before: $before
        after: $after
        orderBy: { direction: DESC, field: POSITION }
      ) {
        totalCount
        pageInfo {
          endCursor
          hasNextPage
          startCursor
          hasPreviousPage
        }
        nodes {
          id
          updatedAt
          content {
            ... on Issue {
              id
              body
              bodyHTML
              closed
              updatedAt
              title
              labels(first: 10) {
                nodes {
                  color
                  id
                  name
                }
              }
              comments(first: 1) {
                nodes {
                  body
                }
              }
            }
          }
          fieldValueByName(name: "Status") {
            ... on ProjectV2ItemFieldSingleSelectValue {
              id
              name
            }
          }
          type
        }
      }
    }
  }
}

# 記事一覧ページ情報取得
query LifeProjectIssuesPageInfo($first: Int!, $before: String, $after: String) {
  node(id: "PVT_kwHOAkr4os4AHb3E") {
    ... on ProjectV2 {
      id
      items(first: $first, before: $before, after: $after) {
        totalCount
        pageInfo {
          endCursor
          hasNextPage
          startCursor
          hasPreviousPage
        }
      }
    }
  }
}

# 記事詳細(Issue詳細)
query IssueDetail($id: ID!) {
  node(id: $id) {
    ... on Issue {
      id
      title
      body
      bodyHTML
      labels(first: 5) {
        nodes {
          color
          id
          name
        }
      }
      updatedAt
      closed
      projectItems(first: 1) {
        totalCount
        nodes {
          fieldValueByName(name: "Status") {
            ... on ProjectV2ItemFieldSingleSelectValue {
              id
              name
            }
          }
        }
      }
      comments(first: 1) {
        nodes {
          body
        }
      }
    }
  }
}

# カテゴリ
query LifeProjectStatusList {
  node(id: "PVT_kwHOAkr4os4AHb3E") {
    ... on ProjectV2 {
      id
      field(name: "Status") {
        ... on ProjectV2SingleSelectField {
          id
          options {
            id
            name
          }
        }
      }
    }
  }
}

# タグ
query LifeRepositoryLabels {
  node(id: "R_kgDOIKnT4g") {
    ... on Repository {
      id
      name
      labels(first: 50) {
        nodes {
          color
          id
          name
          updatedAt
        }
      }
    }
  }
}

# 廃止
# リポジトリのファイル取得
# query LifeRepository {
#   repository(owner: "yumemi-omi", name: "life") {
#     object(expression: "main:") {
#       ... on Tree {
#         entries {
#           name
#           type
#           object {
#             ... on Tree {
#               entries {
#                 name
#                 type
#                 object {
#                   ... on Blob {
#                     byteSize
#                     isBinary
#                     id
#                     text
#                   }
#                 }
#               }
#             }
#           }
#         }
#       }
#     }
#   }
# }
